version: "3"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:alpine
    container_name: node-app
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      .env
     
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:7.0.14-alpine3.18
    container_name: redis
    ports:
      - "6379:6379"